### PR TITLE
mafft has been added

### PR DESCRIPTION
**Pull request by ypriverol**
Another Container @osallou

### CODE REVIEW

**Comment by osallou** [comment]
about.license field is not in spdx list: https://spdx.org/licenses/, if it is a typo error, please fix it. If this is not a standard license, then ignore this message.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
Found an existing bioconda package for this software (https://bioconda.github.io/recipes/mafft/README.html), is this the same, then you should update the recipe in bioconda to avoid duplicates.

**Comment by ypriverol** [comment]
https://github.com/BioContainers/containers/issues/160

**Comment by osallou** [comment]
about.license field is not in spdx list: https://spdx.org/licenses/, if it is a typo error, please fix it. If this is not a standard license, then ignore this message.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
Found an existing bioconda package for this software (https://bioconda.github.io/recipes/mafft/README.html), is this the same, then you should update the recipe in bioconda to avoid duplicates.

**Pull request merged**
