### PR TITLE
new rsat version 20230825

### PR DESCRIPTION
**Pull request by eead-csic-compbio**
This PR adds a new version (20230825) of the Docker BioContainer with the RSAT software. 
The only change in the Dockerfile is LABEL software.version="20230825" , there have been some changes in source repo (https://github.com/rsa-tools/rsat-code).

### CODE REVIEW

**Review by osallou — COMMENTED** [review]
You clone rsat git repos, but you do not use git tags/branches, so running recipe will install "latest", this is not reproducible..

**Comment by eead-csic-compbio** [comment]
Thanks @osallou , I have now added a tag to the clone command, feedback welcome,
Bruno

**Comment by eead-csic-compbio** [comment]
Thanks for your help @osallou .
We found another bug not picked up during testing, should I open another PR or can we re-open this one?

**Comment by osallou** [comment]
once merged, pr should not be re-opened, so a new one :-)

**Pull request merged**
