### PR TITLE
Create Dockerfile for r-metamix

### PR DESCRIPTION
**Pull request by sarah-buddle**
# Submitting a Container
 
 (If you're requesting for a new container, please check the procedure described [here](https://github.com/BioContainers/containers#241-how-to-request-a-container).  
 
 ## Check BioContainers' Dockerfile [specifications](https://github.com/BioContainers/specs)  
 ## Checklist
 
 1. Misc
 - [ ] My tool doesn't exist in [BioConda](#make-sure-your-tool-isnt-already-present-in-bioconda)   
 - [ ] The image can be built   
 
 2. [Metadata](#check-biocontainers-dockerfile-metadata)  
 - [x] LABEL base_image  
 - [x] LABEL version
 - [x] LABEL software.version  
 - [x] LABEL about.summary  
 - [x] LABEL about.home  
 - [x] LABEL about.license   
 - [x] MAINTAINER  
 
 3. Extra (optionals)
  - [ ] I have written tests in test-cmds.txt  
  - [x] LABEL extra.identifier    
  - [x] LABEL about.documentation   
  - [x] LABEL about.license_file
  - [x] LABEL about.tags   
 
 
 ## Check [BioContainers'](https://github.com/BioContainers/specs) Dockerfile metadata

### CODE REVIEW

**Comment by osallou** [comment]
@sarah-buddle build failed, did you try to build it locally?

**Comment by sarah-buddle** [comment]
@osallou I have made a correction and it is now building locally

**Comment by osallou** [comment]
ok, you just need to fix typo in license to be spdx compliant (see https://spdx.org/licenses/ :  GPL-3.0-or-later for example)

and I'll merge!

**Comment by sarah-buddle** [comment]
Thanks, I've changed it to GPL-3.0-or-later

**Comment by osallou** [comment]
done! thanks @sarah-buddle

**Comment by sarah-buddle** [comment]
Thanks @osallou!

**Pull request merged**
