### PR TITLE
Openms2.2

### PR DESCRIPTION
**Pull request by hroest**
replaces #194 - uses the same approach as the TPP and other tools with a fixed .zip file

### CODE REVIEW

**Comment by hroest** [comment]
I guess we would want to store the zip file somewhere different

**Comment by prvst** [comment]
Thanks
I guess we can store the zip folder on the biocontainers account for now

**Comment by bgruening** [comment]
@hroest was anything wrong with https://quay.io/repository/biocontainers/openms?tab=tags ?
This is now redundant as far as I can tell.

**Comment by hroest** [comment]
@bgruening ok, I think I was not aware of these containers, I have only seen openms 1.11 and 2.0 here in the repo so I didnt know these containers existed

**Pull request merged**
