### PR TITLE
Version bump (important to have in preparation for NF-CORE integration)

### PR DESCRIPTION
**Pull request by lassefolkersen**
# Submitting a Container
 
 (If you're requesting for a new container, please check the procedure described [here](https://github.com/BioContainers/containers#241-how-to-request-a-container).  
 
 ## Check BioContainers' Dockerfile [specifications](https://github.com/BioContainers/specs)  
 ## Checklist
 
 1. Misc
 - [x] My tool doesn't exist in [BioConda](#make-sure-your-tool-isnt-already-present-in-bioconda)   
 - [x] The image can be built   
 
 2. [Metadata](#check-biocontainers-dockerfile-metadata)  
 - [x] LABEL base_image  
 - [x] LABEL version
 - [x] LABEL software.version  
 - [x] LABEL about.summary  
 - [x] LABEL about.home  
 - [x] LABEL about.license   
 - [x] MAINTAINER  
 
 3. Extra (optionals)
  - [ ] I have written tests in test-cmds.txt  
  - [x] LABEL extra.identifier    
  - [x] LABEL about.documentation   
  - [x] LABEL about.license_file
  - [x] LABEL about.tags   
 
 
 ## Check [BioContainers'](https://github.com/BioContainers/specs) Dockerfile metadata

### CODE REVIEW

**Comment by lassefolkersen** [comment]
@osallou thanks a lot, for quick reply! It's for the purpose of a merge into nf-core ([pull request WIP](https://github.com/nf-core/modules/pull/882)). Harshil Patel, from nf-core, suggested I asked you about also making a singularity and host at biocontainers, if that's possible? The same Dockerfile recipe will work and has been tested for it, I just use the code below - but have you any way to get something similar working on biocontainers?

```
docker run -v /var/run/docker.sock:/var/run/docker.sock -v \
  "/home/ec2-user/:/output" --privileged -t --rm \
  quay.io/singularity/docker2singularity:v3.4.1 \
  lassefolkersen/impute-me:v1.0.7
  ```

**Comment by osallou** [comment]
singularity are already automatically generated

prev version for example https://containers.biocontainers.pro/s3/SingImgsRepo/imputeme/vv1.0.4_cv1/

**Comment by lassefolkersen** [comment]
Hi @osallou - Sorry to sound impatient (I'm not! - just asking to see if I understand the system 😄), but I can't see the new version (yet? or needs a bump, or?)
https://containers.biocontainers.pro/s3/SingImgsRepo/imputeme/

**Comment by osallou** [comment]
it should.... must be an issue after our transition to a new cloud

I will have a look

**Comment by osallou** [comment]
humm a disk space problem when generating singularity image

**Comment by osallou** [comment]
conversion uses more than 12G disk....

**Comment by osallou** [comment]
image by itself is almost 5Go, should be optimized....

**Comment by lassefolkersen** [comment]
I see - it's because it requires a lot of permanent data for the imputation-step, and it's a trade-off with user-friendly-ness vs having an extra external download step. I've followed the same thoughts as similar [analysis-engines](https://github.com/genepi/imputationserver-docker), where the basic reference data is inside, and then there's options for using external (even) bigger data. Will it help to delete v1.0.4?

**Comment by osallou** [comment]
nope, it is a built time issue, not enough disk on build server

**Comment by osallou** [comment]
trying to get bit more disk space... will see

**Comment by osallou** [comment]
I could increase disk size... sing image is available now

**Comment by lassefolkersen** [comment]
Thanks! I owe you one. Promise the containers will aim for growing smaller in the future (and also, now that it's running in nf-core, I think it'll be a while for next update).

**Pull request merged**
