### PR TITLE
Reference to PeptideShaker 1.16.17

### PR DESCRIPTION
**Pull request by CarlosHorro**
Reference to PeptideShaker 1.16.17 (adds some bugfixes).
Fixed license and license_file labels.
Added "biotools" to tags label.

### CODE REVIEW

**Comment by osallou** [comment]
Found a biotools entry matching the software name (https://bio.tools/PeptideShaker), if this is the same software, please add the biotools label to your Dockerfile

**Comment by CarlosHorro** [comment]
I already added it.

**Comment by CarlosHorro** [comment]
Hi,
I think I'm missing something, as
https://hub.docker.com/r/biocontainers/peptideshaker/~/dockerfile/

still references to version 1.10.3 instead to the last one... do you know what am I missing, please?

**Comment by osallou** [comment]
@CarlosHorro  I gonna check

**Comment by osallou** [comment]
In tags tab, you can see available tags:
v1.16.17_cv1

The shown Dockerfile refers to the *old* manually builds. Now they are automatically build and images are pushed to Dockerhub. However, pushing an image do not set/update the Dockerfile in DockerHub.

**Comment by CarlosHorro** [comment]
@osallou thank you very much!

**Comment by CarlosHorro** [comment]
Sorry but it seems that there is still something wrong. If we try to download the biocontainer in the usual way, with: 
docker pull biocontainers/peptideshaker
it tries to use the default tag, 'latest', and the command gives an error:

Using default tag: latest
Error response from daemon: manifest for biocontainers/peptideshaker:latest not found

However, it works if we specify the tag referencing to the last version:
docker pull biocontainers/peptideshaker:v1.16.17_cv1

**Comment by osallou** [comment]
this is expected behavior, you should always specify the release.
*latest* in docker refers to latest build, not latest version (you could rebuild an older release for example).
So you never know which release you are using.

So we remove the latest here. And for reproducibility, you should always specify a version.

**Pull request merged**
