### PR TITLE
Updated ilastik cpu version to 1.4.0

### PR DESCRIPTION
**Pull request by FloWuenne**
# Submitting a new version of an existing Container
 
@sunyi000 
@k-dominik
 
This is updating ilastik cpu version to 1.4.0, the newest stable release. 

Based off #498, simply replaced the relevant version information.

### CODE REVIEW

**Comment by bgruening** [comment]
@FloWuenne if you like please add a `test-cmds.txt` to test your container.

**Comment by FloWuenne** [comment]
The old version didn't have test-cmds.txt so I don't think its strictly necessary. Where would I find info on what to put into the test-cmds.txt file?

**Comment by bgruening** [comment]
Not strictly necessary :)
Its a simple CLI command that is run in the container.

Similar to the conda command tests.

**Comment by FloWuenne** [comment]
I added the same test command I added to the nf-core modules, basically should print the version number of ilastik.

**Comment by osallou** [comment]
you refer to /ilastik-release/run_ilastik.sh but you install in /opt/ilastik-1xxxxx

**Comment by FloWuenne** [comment]
> you refer to /ilastik-release/run_ilastik.sh but you install in /opt/ilastik-1xxxxx

Absolutely, sorry I had copied the command from the tests I had written for another docker container! 
Gonna build the container locally and test the corrected version and then push the update!

**Comment by osallou** [comment]
no pb :-)

**Comment by FloWuenne** [comment]
Fixed it. Testing this test-cmd.txt using the local container worked!

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks.

**Comment by FloWuenne** [comment]
Thanks for merging. Did the action fail because I deleted the branch? I hope not 🤭
https://github.com/BioContainers/containers/actions/runs/4304948666

**Comment by k-dominik** [comment]
thx @FloWuenne for updating the container! :)

**Comment by osallou** [comment]
> Thanks for merging. Did the action fail because I deleted the branch? I hope not hand_over_mouth https://github.com/BioContainers/containers/actions/runs/4304948666

should not, it has been merged so should be ok..... I am looking at the issue, thanks anyway

**Comment by osallou** [comment]
ok, pb is merge did not squash the commits of the MR, CI looks at last commit file differences...

**Comment by FloWuenne** [comment]
Thanks for fixing it @osallou !!!

**Pull request merged**
