### PR TITLE
Container for NCBI datasets CLI

### PR DESCRIPTION
**Pull request by priyanka-surana**
# Submitting a Container
 
 (If you're requesting for a new container, please check the procedure described [here](https://github.com/BioContainers/containers#241-how-to-request-a-container).  
 
 ## Check BioContainers' Dockerfile [specifications](https://github.com/BioContainers/specs)  
 ## Checklist
 
 1. Misc
 - [x] My tool doesn't exist in [BioConda](#make-sure-your-tool-isnt-already-present-in-bioconda)   
 - [x] The image can be built   
 
 2. [Metadata](#check-biocontainers-dockerfile-metadata)  
 - [x] LABEL base_image  
 - [x] LABEL version
 - [x] LABEL software.version  
 - [x] LABEL about.summary  
 - [x] LABEL about.home  
 - [x] LABEL about.license   
 - [x] MAINTAINER  
 
 3. Extra (optionals)
  - [ ] I have written tests in test-cmds.txt  
  - [ ] LABEL extra.identifier    
  - [x] LABEL about.documentation   
  - [ ] LABEL about.license_file
  - [ ] LABEL about.tags   
 
 
 ## Check [BioContainers'](https://github.com/BioContainers/specs) Dockerfile metadata

### CODE REVIEW

**Comment by priyanka-surana** [comment]
@osallou How long before containers are available on quay.io? Thank you.

**Comment by osallou** [comment]
Containers built here are on dockerhub, on quay io are containers built from bioconda packages

**Comment by osallou** [comment]
Containers built here are on dockerhub, on quay io are containers built from conda packages

should be available now

**Comment by priyanka-surana** [comment]
There is a package on conda-forge but the container was not automatically built. Is there something that needs to be done to trigger it? I know bioconda is automated, but my experience with other conda channels is limited.

**Comment by osallou** [comment]
nope, bioconda has its own CI, conda forge is different, no container build nor relation to biocontainers

**Pull request merged**
