### PR TITLE
Add vcf2hapmap

### PR DESCRIPTION
**Pull request by avengerpb**
* This commit is to add new tool for biocontainer

* Docker image and container can be built from the Dockerfile

* To test the container, the following command can be used: vcf2FastaAndHapmap.sh inFile outFile

### CODE REVIEW

**Comment by prvst** [comment]
I noticed that you are using alpine linux as a base image, can you change to our biocontainers base image ? Also, if possible, we should keep the binaries and/or program scripts in another place, different from where the image is.

**Comment by prvst** [comment]
hey @avengerpb , any progress ?

**Comment by avengerpb** [comment]
Thank you for asking, I am stop working on this work. There will be another person take the responsibility to develop this.

**Comment by prvst** [comment]
OK, so for now Im going to close your PR, feel free to ping us again if you change your mind

**Pull request closed without merging**
