### PR TITLE
Fix typos in the README

### PR DESCRIPTION
**Pull request by kelly-sovacool**
* Fix grammar under "What is BioContainers?"
* Fix link to Travis CI under "Objectives and Goals" and add an Oxford comma.
* Fix grammer and add hypens under "How to use a BioContainer ".
* Fix typos under "Biocontainers Architecture"
* Fix grammar under "How to Request a Container".
* Fix grammar under "Use a Biocontainer".
* Fix grammar under "What do I need to develop?"
* Removed the phrase "Having all in hands" to improve sentence flow under "How to create a Docker based Biocontainer?" and "How to create a rkt based Biocontainer?".

### CODE REVIEW

**Comment by osallou** [comment]
You're trying to update a file not related to a container: README.md, this is forbidden

**Comment by osallou** [comment]
You're trying to update a file not related to a container: README.md, this is forbidden

**Comment by osallou** [comment]
Merged, thanks

**Comment by kelly-sovacool** [comment]
Okay. How would you prefer we make small fixes like this in the future if not via pull requests?

**Comment by osallou** [comment]
pull requests are fine.

**Pull request merged**
