### PR TITLE
Cellpose update: 3.0.1 --> 3.1.0

### PR DESCRIPTION
**Pull request by kbestak**
# Submitting a Container
 
 (If you're requesting for a new container, please check the procedure described [here](https://github.com/BioContainers/containers#241-how-to-request-a-container).  
 
 ## Check BioContainers' Dockerfile [specifications](https://github.com/BioContainers/specs)  
 ## Checklist
 
 1. Misc
 - [x] My tool doesn't exist in [BioConda](#make-sure-your-tool-isnt-already-present-in-bioconda)   
 - [x] The image can be built   
 
 2. [Metadata](#check-biocontainers-dockerfile-metadata)  
 - [x] LABEL base_image  
 - [x] LABEL version
 - [x] LABEL software.version  
 - [x] LABEL about.summary  
 - [x] LABEL about.home  
 - [x] LABEL about.license   
 - [x] MAINTAINER  
 
 3. Extra (optionals)
  - [ ] I have written tests in test-cmds.txt  
  - [x] LABEL extra.identifier    
  - [x] LABEL about.documentation   
  - [x] LABEL about.license_file
  - [ ] LABEL about.tags   
 
 
 ## Check [BioContainers'](https://github.com/BioContainers/specs) Dockerfile metadata

Changes: https://github.com/MouseLand/cellpose/releases/tag/v3.1.0

### CODE REVIEW

**Comment by kbestak** [comment]
Hi Biocontainers team,
I have two questions connected to the PR above:
1. What would be the best way to add GPU acceleration support to the container? I was able to build an image from an nvidia base image instead of python (as is in the Dockerfile above) that can utilize available GPUs, however the size is then much larger.
2. Is it acceptable to have a CPU-only and GPU option for the same version of a tool?
Thank you!

**Comment by mboudet** [comment]
Hi,

I believe the issue withe GPU support is that you need to match the CUDA version in the container to the host GPU driver, so it's difficult to build in a docker (you would need to build a container for each major cuda version).

Not sure if they now manage backward / forward version support.

As for building separate version, if there are no other choices (ie, the tool built in GPU mode cannot support CPU mode), I'm not against it.

**Comment by kbestak** [comment]
From testing, the container with CUDA can still run on CPU if GPU is not provided, however since the container is then much larger, I thought it would be good to have both. I can build both and come back with the estimated container size.

**Comment by mboudet** [comment]
Ok. There is still the issue of the CUDA compatibility. I'd rather not have to build a container for each CUDA main version..

**Comment by sminot** [comment]
I would love to be able to use cellulose 3.1.0, if there is any way to merge this PR without waiting on a solution for CUDA

**Comment by kbestak** [comment]
From my side, I'd suggest setting the CUDA topic aside in that case.

**Comment by mboudet** [comment]
That's fine by me

**Comment by mboudet** [comment]
Alright, should be fine to merge. Thanks for your contribution.

**Pull request merged**
