### PR TITLE
Added Hmmer 3.2 package

### PR DESCRIPTION
**Pull request by biomadeira**
...this is installed with bioconda.

### CODE REVIEW

**Comment by osallou** [comment]
about.license field is not in spdx list: https://spdx.org/licenses/, if it is a typo error, please fix it. If this is not a standard license, then ignore this message.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
Found an existing bioconda package for this software (https://bioconda.github.io/recipes/hmmer/README.html), is this the same, then you should update the recipe in bioconda to avoid duplicates.

**Comment by osallou** [comment]
No hmmer/3.2/test-cmds.txt (test file) present, skipping tests

**Comment by biomadeira** [comment]
@osallou This version is now provided in bioconda https://bioconda.github.io/recipes/hmmer/README.html 

Thanks!

**Comment by osallou** [comment]
about.license field is not in spdx list: https://spdx.org/licenses/, if it is a typo error, please fix it. If this is not a standard license, then ignore this message.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
Found an existing bioconda package for this software (https://bioconda.github.io/recipes/hmmer/README.html), is this the same, then you should update the recipe in bioconda to avoid duplicates.

**Comment by osallou** [comment]
No hmmer/3.2/test-cmds.txt (test file) present, skipping tests

**Pull request closed without merging**
