### PR TITLE
Added FASTA 36.3.8 package

### PR DESCRIPTION
**Pull request by biomadeira**
...this is installed with bioconda.

### CODE REVIEW

**Comment by osallou** [comment]
Found a biotools entry matching the software name (https://bio.tools/FASTA), if this is the same software, please add the extra.identifier.biotools label to your Dockerfile

**Comment by osallou** [comment]
No fasta/36.3.8/test-cmds.txt (test file) present, skipping tests

**Comment by biomadeira** [comment]
@osallou This version is now provided in bioconda https://bioconda.github.io/recipes/fasta3/README.html 

Thanks!

**Comment by osallou** [comment]
Found a biotools entry matching the software name (https://bio.tools/FASTA), if this is the same software, please add the extra.identifier.biotools label to your Dockerfile

**Comment by osallou** [comment]
No fasta/36.3.8/test-cmds.txt (test file) present, skipping tests

**Pull request closed without merging**
