### PR TITLE
new rsat version 20240507, tested in local Docker

### PR DESCRIPTION
**Pull request by eead-csic-compbio**
This PR adds a new version of the Docker BioContainer with the RSAT software, which now ships wit the code corresponding to tag 20240507  in source repo (https://github.com/rsa-tools/rsat-code). Accordingly, the Dockerfile now contains LABEL software.version="20240507".

The two main updates are:

 + The container can now be run non-interactively, it has been tested in local Docker. 
+ `install-organisms` has been updated to support again the installation of genomes from the NCBI. It was tested by  @jvanheld  was tested by installing bacterial genomes on the Bacterial RSAT server.

Example non-interactive calls would be: 
 
    docker run -v $PWD:/home/rsat_user -v $PWD/out:/home/rsat_user/out rsat:20240507 peak-motifs -i test.fa -outdir out -prefix test

    docker run -v $PWD:/home/rsat_user -v $PWD/out:/home/rsat_user/out rsat:20240507 peak-motifs -i test.fa -outdir out -prefix test -motif_db footDB transfac /packages/rsat/public_html/motif_databases/footprintDB/footprintDB.plants.motif.tf

Note the examples require binding two folders: 
  1. The current folder from where the container is called (`$PWD`). This allows processing any FASTA file in the current directory.
  2. The folder to save the results (`out/`). This should point to an existing local folder where anybody can write (chmod 777). 

@medinaale @morganeTC @najlaksouri

### CODE REVIEW

**Comment by eead-csic-compbio** [comment]
Hi @ievarau, please use this PR to add any comments you might have during your tests

**Comment by ievarau** [comment]
- Tested building. Success. Important to build using Docker (Podman won't do).
- Tested running container non-interactively with two example calls provided above. Works as expected.
- Tested within Snakemake pipeline. Works as expected as well.

All in all, peak-motifs with this container version works as expected.

**Comment by eead-csic-compbio** [comment]
This PR is read y to be reviewed by somebody from BioContainers, thanks

**Comment by eead-csic-compbio** [comment]
Hi @mboudet , please let us know if there's anything you need from us

**Comment by mboudet** [comment]
Sorry for the delay, last week was mostly bank holidays here.

One quick question: any reason for installing git in a separate ` apt-get install` step?  (Ie line 91 instead of 43)
(This is not blocking, just for curiosity).

**Comment by eead-csic-compbio** [comment]
> Sorry for the delay, last week was mostly bank holidays here.
> 
> One quick question: any reason for installing git in a separate ` apt-get install` step? (Ie line 91 instead of 43) (This is not blocking, just for curiosity).

I guess it was  to make it clear that the installation of RSAT would be done using git

**Comment by mboudet** [comment]
Alright. Thank you for your contribution.

**Pull request merged**
