### PR TITLE
adding pymol-jupyter

### PR DESCRIPTION
**Pull request by ocramz**

### CODE REVIEW

**Comment by prvst** [comment]
Thanks @ocramz. 
Before approving I just need you to change two things:
1) change the version number from 0.1 to 1
2) move the MAINTAINER tag to the end of the file, you can use one of the available tools as an example.

**Comment by ocramz** [comment]
@prvst done!

**Comment by prvst** [comment]
@ocramz thanks. Welcome to the project !

**Comment by sauloal** [comment]
@ocramz , wouldn't you rather keep the project (dockerfile, etc) in your own repository?
I really like the lengthy explanation readme. this won't be available here. 

What do you think?

@prvst  @ypriverol ?

**Comment by ocramz** [comment]
@sauloal  I will keep both in fact, at least for the time being. Your good work on fixing/reshaping the dockerfile in order to build on top of `biodckr` deserves to be here, whereas in the `main` branch I have at https://github.com/ocramz/jupyter-docker-pymol the dockerfile is somewhat leaner, since it builds directly upon a Jupyter project image.

Of course, part of the readme you mention applies to BioDocker as well (docker requirements and setup, pulling and running). Perhaps we can adapt it?

**Comment by sauloal** [comment]
@ocramz . I just had an idea. why not create a dockerfile on our repo that starts from your repo?

a single line dockerfile:

``` dockerfile
FROM ocramz/jupyter-docker-pymol
```

**Pull request merged**
