### PR TITLE
Test docker file to container repo

### PR DESCRIPTION
**Pull request by frank-nankivell**
# Submitting a test container to the Biocontainers repo

I assume this PR won't pass -  but submitting anyway to test the system

Frank

### CODE REVIEW

**Comment by osallou** [comment]
can't modify multiple containers in a same pull request

**Comment by osallou** [comment]
you should remove frank-test from your PR...

**Comment by frank-nankivell** [comment]
Sorry - I have actually made this PR to the wrong repo - supposed to be a forked rep genomicsengland/containers

**Comment by osallou** [comment]
can't modify multiple containers in a same pull request

**Pull request closed without merging**
