### PR TITLE
Pin the version to make the build reproducible

### PR DESCRIPTION
**Pull request by muffato**
There are now new versions of `ncbi-datasets-cli` in conda-forge, so this specific version's Dockerfile needs to install the right one.

### CODE REVIEW

**Review by osallou — CHANGES_REQUESTED** [review]
As dockerfile is updated, label version should be increased, eg version=2

**Comment by muffato** [comment]
Done, thank you !

**Comment by osallou** [comment]
@muffato merged, thanks!

**Comment by jennahamlin** [comment]
There are now new versions of ncbi-datasets-cli in conda-forge version 15.3.0, can this be updated in the dockerfile by changing `ncbi-datasets-cli=14.2.2` to `ncbi-datasets-cli=15.3.0` in the final line (`RUN conda install -c conda-forge ncbi-datasets-cli=15.3.0`

Thank you

**Comment by osallou** [comment]
Hi, simply propose a pull request with change in recipe and updating the software.version label

**Comment by osallou** [comment]
But, if there is a conda package, there is a related docker in biocontainers, all bioconda packages have theur biocontainers counterpart, why creating a new one here?

**Comment by jennahamlin** [comment]
@osallou thanks for the quick response. This is probably due to may lack of knowledge, but how does one find that specific version in biocontainers? I looked on: https://quay.io/repository/biocontainers/ncbi-datasets-cli?tab=tags and did not see version 15.3.0 only upto version 14.26.0

**Comment by osallou** [comment]
Oh my fault, conda forge != bioconda ....

Maybe best however, as conda package based, would be to get this in bioconda....

But if you do not feel to do this in bioconda, just update recipe to match release and 

* update software.version dockerfile label and command to upload needed version
* update directory where dockerfile is to match software version too

**Pull request merged**
