### PR TITLE
Added PaddleHelix 1.0.1 Dockerfile

### PR DESCRIPTION
**Pull request by rijulsr**
# Submitting a Container
 
 (If you're requesting for a new container, please check the procedure described [here](https://github.com/BioContainers/containers#241-how-to-request-a-container).  
 
 ## Check BioContainers' Dockerfile [specifications](https://github.com/BioContainers/specs)  
 ## Checklist
 
 1. Misc
 - [x] My tool doesn't exist in [BioConda](#make-sure-your-tool-isnt-already-present-in-bioconda)   
 - [ ] The image can be built   
 
 2. [Metadata](#check-biocontainers-dockerfile-metadata)  
 - [x] LABEL base_image  
 - [x] LABEL version
 - [x] LABEL software.version  
 - [x] LABEL about.summary  
 - [x] LABEL about.home  
 - [x] LABEL about.license   
 - [ ] MAINTAINER  
 
 3. Extra (optionals)
  - [ ] I have written tests in test-cmds.txt  
  - [ ] LABEL extra.identifier    
  - [x] LABEL about.documentation   
  - [x] LABEL about.license_file
  - [ ] LABEL about.tags   
 
 
 ## Check [BioContainers'](https://github.com/BioContainers/specs) Dockerfile metadata

### CODE REVIEW

**Comment by mboudet** [comment]
This is the same PR as before, with the same issue concerning the conda version.

In addition
* The license is wrong (should be CC-BY-NC-SA-4.0)
* The biotool ID does not exists

**Comment by rijulsr** [comment]
so what exactly needs to be done on my part? to make it all right.

**Comment by mboudet** [comment]
Nothing. The design of paddlepaddle-gpu makes it that you would have to build a separate docker image for each supported cuda version, or adjust the lib version at runtime.
Frankly, a docker image is not really a good fit for this.

**Comment by rijulsr** [comment]
You are right, I just wanted to create the docker image, becuase I want to integrate this tool somewhere at backend, but it seems like even having a docker image for this would of no use, given the complications with the version control.

**Pull request closed without merging**
