### PR TITLE
Added kast 1.0.0

### PR DESCRIPTION
**Pull request by martinjvickers**
# Submitting a Container
 
 (If you're requesting for a new container, please check the procedure described [here](https://github.com/BioContainers/containers#241-how-to-request-a-container).  
 
 ## Check BioContainers' Dockerfile [specifications](https://github.com/BioContainers/specs)  
 ## Checklist
 
 1. Misc
 - [ ] My tool doesn't exist in [BioConda](#make-sure-your-tool-isnt-already-present-in-bioconda)   
 - [ ] The image can be built   
 
 2. [Metadata](#check-biocontainers-dockerfile-metadata)  
 - [ ] LABEL base_image  
 - [ ] LABEL version
 - [ ] LABEL software.version  
 - [ ] LABEL about.summary  
 - [ ] LABEL about.home  
 - [ ] LABEL about.license   
 - [ ] MAINTAINER  
 
 3. Extra (optionals)
  - [ ] I have written tests in test-cmds.txt  
  - [ ] LABEL extra.identifier    
  - [ ] LABEL about.documentation   
  - [ ] LABEL about.license_file
  - [ ] LABEL about.tags   
 
 
 ## Check [BioContainers'](https://github.com/BioContainers/specs) Dockerfile metadata

### CODE REVIEW

**Comment by martinjvickers** [comment]
Have I made a mistake with this pull request? I'm not sure why the tests/checks have failed?

**Comment by osallou** [comment]
You set software name as KAST, should be kast (lowercase) to match dir name, and docker names should be lowercase

**Comment by martinjvickers** [comment]
> You set software name as KAST, should be kast (lowercase) to match dir name, and docker names should be lowercase

Thank you :+1:  It's always the obvious errors that get me!

**Comment by osallou** [comment]
You define a biotools entry, but it does not exists in biotools.
Either remove label or add entry in bio.tools

**Comment by osallou** [comment]
Merged, but should avoid CMD

Defining cmd/entrypoint creates issues with some workflow tools executing container with the full command, which in this case is concatenaed to the docker defined command (kast kast xxx)

We expect none, and user/tool specifies full command

**Comment by martinjvickers** [comment]
Is there a reason why https://hub.docker.com/r/biocontainers/kast has the pull command as `docker pull biocontainers/kast` which doesn't work?

```
$ sudo docker pull biocontainers/kast
Using default tag: latest
Error response from daemon: manifest for biocontainers/kast:latest not found: manifest unknown: manifest unknown
```

I know I can get it to work with specifying the version flag;

`$ sudo docker pull biocontainers/kast:v1.0.0_cv1`

however shouldn't the pull command from docker hub also work?

**Comment by osallou** [comment]
There is no latest tag, you must always specify the tag

The eason is latest may not be the more recent upstream version, but the last build, which could be a builld on an older version

**Pull request merged**
