### PR TITLE
shotmap has been added. 

### PR DESCRIPTION
**Pull request by ypriverol**
https://github.com/BioContainers/containers/issues/171

### CODE REVIEW

**Comment by osallou** [comment]
about.license field is not in spdx list: https://spdx.org/licenses/, if it is a typo error, please fix it. If this is not a standard license, then ignore this message.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by ypriverol** [comment]
@osallou I think this PR is ready now.

**Comment by osallou** [comment]
will rebuild all the containers (well most of them). Will merge once some builds are over

**Pull request merged**
