### PR TITLE
New container version.

### PR DESCRIPTION
**Pull request by ypriverol**
# Submitting a Container
 
 (If you're requesting for a new container, please check the procedure described [here](https://github.com/BioContainers/containers#241-how-to-request-a-container).  
 
 ## Check BioContainers' Dockerfile [specifications](https://github.com/BioContainers/specs)  
 ## Checklist
 
 1. Misc
 - [ ] My tool doesn't exist in [BioConda](#make-sure-your-tool-isnt-already-present-in-bioconda)   
 - [ ] The image can be built   
 
 2. [Metadata](#check-biocontainers-dockerfile-metadata)  
 - [ ] LABEL base_image  
 - [ ] LABEL version
 - [ ] LABEL software.version  
 - [ ] LABEL about.summary  
 - [ ] LABEL about.home  
 - [ ] LABEL about.license   
 - [ ] MAINTAINER  
 
 3. Extra (optionals)
  - [ ] I have written tests in test-cmds.txt  
  - [ ] LABEL extra.identifier    
  - [ ] LABEL about.documentation   
  - [ ] LABEL about.license_file
  - [ ] LABEL about.tags   
 
 
 ## Check [BioContainers'](https://github.com/BioContainers/specs) Dockerfile metadata

### CODE REVIEW

**Comment by osallou** [comment]
can't modify multiple containers in a same pull request

**Comment by osallou** [comment]
Look at files changed. With submodule you have 3 containers here

**Comment by osallou** [comment]
in your PR you modify .gitignore and set .gitsubmodules to empty, removing previous declared submodules.
Please modify only the crux dir, do not modifiy .git related files , this is forbidden for PRs by our system

**Comment by ypriverol** [comment]
Done.

**Comment by osallou** [comment]
No crux/3.2/test-cmds.txt (test file) present, skipping tests

**Comment by osallou** [comment]
No crux/3.2/test-cmds.txt (test file) present, skipping tests

**Pull request merged**
