### PR TITLE
Adding eosc-pilot/1.0-remastering container

### PR DESCRIPTION
**Pull request by pditommaso**
# Submitting a Container
 
 (If you're requesting for a new container, please check the procedure described [here](https://github.com/BioContainers/containers#241-how-to-request-a-container).  
 
 ## Check BioContainers' Dockerfile [specifications](https://github.com/BioContainers/specs)  
 ## Checklist
 
 1. Misc
 - [x] My tool doesn't exist in [BioConda](#make-sure-your-tool-isnt-already-present-in-bioconda)   
 - [x] The image can be built   
 
 2. [Metadata](#check-biocontainers-dockerfile-metadata)  
 - [x] LABEL base_image  
 - [x] LABEL version
 - [x] LABEL software.version  
 - [x] LABEL about.summary  
 - [x] LABEL about.home  
 - [x] LABEL about.license   
 - [x] MAINTAINER  
 
 3. Extra (optionals)
  - [ ] I have written tests in test-cmds.txt  
  - [ ] LABEL extra.identifier    
  - [ ] LABEL about.documentation   
  - [ ] LABEL about.license_file
  - [ ] LABEL about.tags   
 
 
 ## Check [BioContainers'](https://github.com/BioContainers/specs) Dockerfile metadata

### CODE REVIEW

**Comment by osallou** [comment]
label software should match directory name (and is linked to container name with its strict rules)
you have: software="EGA-CRG EOSC-Pilot project"
should be: software=eosc-pilot

**Comment by osallou** [comment]
please specify in about.license_file the location of the license file in the container, or a url to license for this release of the software.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifiers.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by pditommaso** [comment]
Fixed.

**Comment by pditommaso** [comment]
> check if tool is not already defined in biotools (https://bio.tools) and add extra.identifiers.biotools label if it exists. If it is not defined, you can ignore this comment.

this is basically a multi tools container including R + picard=2.9 + bwa=0.7.15 + fastqc=0.11.5 + sambamba=0.6.6 + tabix

Should I include a biotools ID for each of them ?

**Comment by osallou** [comment]
No eosc-pilot/1.0-remastering/test-cmds.txt (test file) present, skipping tests

**Comment by osallou** [comment]
no biotools id is needed it as a multi tool.
This is an automated comment based on dockerfile analysis...  :-)


merging it, thanks

**Comment by osallou** [comment]
please specify in about.license_file the location of the license file in the container, or a url to license for this release of the software.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifiers.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
No eosc-pilot/1.0-remastering/test-cmds.txt (test file) present, skipping tests

**Pull request merged**
