### PR TITLE
Added NCBI Blast 2.7.1 package

### PR DESCRIPTION
**Pull request by biomadeira**
...this is installed with bioconda.

### CODE REVIEW

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
Hi
If package is available via bioconda, then there is already a container available, all bioconda packaces generate one

**Comment by biomadeira** [comment]
@osallou This version is now provided in bioconda https://bioconda.github.io/recipes/blast/README.html 

Thanks!

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Pull request closed without merging**
