### PR TITLE
add interproscan container (tools only)

### PR DESCRIPTION
**Pull request by ghost**
This PR is a proposal for InterProScan Docker container.
At the moment it based on Ubuntu image but in the future I will try to optimize it and use alpine
This container provide full environment and binaries. Reference databases must be downloaded separately and mounted as a volume.

To test

automated build in https://hub.docker.com/r/olat/interproscan/
```
$ wget ftp://ftp.ebi.ac.uk/pub/databases/metagenomics/iprscan/5/5.30-69.0/alt/interproscan-data-5.30-69.0.tar.gz
$ wget ftp://ftp.ebi.ac.uk/pub/databases/metagenomics/iprscan/5/5.30-69.0/alt/interproscan-data-5.30-69.0.tar.gz.md5
$ md5sum -c interproscan-data-5.30-69.0.tar.gz.md5
$ tar -zxf interproscan-data-5.30-69.0.tar.gz

$ docker run --rm --name interproscan -v $PWD:/mydata -v $PWD/interproscan-5.30-69.0/data:/opt/interproscan/data olat/interproscan ./interproscan.sh -dp -f tsv  -o /mydata/test_out.ipr -i test_proteins.fasta
Unable to find image 'olat/interproscan:latest' locally
latest: Pulling from olat/interproscan
8ee29e426c26: Pull complete 
6e83b260b73b: Pull complete 
e26b65fd1143: Pull complete 
40dca07f8222: Pull complete 
b420ae9e10b3: Pull complete 
2fe174cae3f5: Pull complete 
61bbec177e30: Pull complete 
3d922df6d667: Pull complete 
Digest: sha256:90499226ebf0bd8a2771d0e8c22818aba7b2181c97cc4d6935152a8a170b30ce
Status: Downloaded newer image for olat/interproscan:latest
29/07/2018 00:10:50:642 Welcome to InterProScan-5.30-69.0
29/07/2018 00:10:56:496 Running InterProScan v5 in STANDALONE mode... on Linux
29/07/2018 00:11:08:846 Loading file /opt/interproscan/test_proteins.fasta
29/07/2018 00:11:08:849 Running the following analyses:
[CDD-3.16,Coils-2.2.1,Gene3D-4.2.0,Hamap-2018_03,MobiDBLite-1.5,Pfam-31.0,PIRSF-3.02,PRINTS-42.0,ProDom-2006.1,ProSitePatterns-2018_02,ProSiteProfiles-2018_02,SFLD-3,SMART-7.1,SUPERFAMILY-1.75,TIGRFAM-15.0]
Pre-calculated match lookup service DISABLED.  Please wait for match calculations to complete...
29/07/2018 00:11:17:170 25% completed
29/07/2018 00:11:33:456 50% completed
29/07/2018 00:11:45:209 75% completed
29/07/2018 00:12:06:938 90% completed
29/07/2018 00:12:34:645 100% done:  InterProScan analyses completed

```

 # Submitting a Container
 
 ## Check BioContainers' Dockerfile [specifications](https://github.com/BioContainers/specs)  
 ## Checklist
 
 1. Misc
 - [x] My tool doesn't exist in [BioConda](#make-sure-your-tool-isnt-already-present-in-bioconda)   
 - [x] The image can be built   
 
 2. [Metadata](#check-biocontainers-dockerfile-metadata)  
 - [x] LABEL base_image  
 - [x] LABEL version
 - [x] LABEL software.version  
 - [x] LABEL about.summary  
 - [x] LABEL about.home  
 - [x] LABEL about.license   
 - [x] MAINTAINER  
 
 3. Extra (optionals)
  - [ ] I have written tests in test-cmds.txt  
  - [x] LABEL extra.identifier    
  - [x] LABEL about.documentation   
  - [x] LABEL about.license_file
  - [x] LABEL about.tags   
 
 
 ## Check [BioContainers'](https://github.com/BioContainers/specs) Dockerfile metadata

### CODE REVIEW

**Comment by osallou** [comment]
please specify in about.license_file the location of the license file in the container, or a url to license for this release of the software.

**Comment by osallou** [comment]
about.license field is not in spdx list: https://spdx.org/licenses/, if it is a typo error, please fix it. If this is not a standard license, then ignore this message.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
please specify in about.license_file the location of the license file in the container, or a url to license for this release of the software.

**Comment by osallou** [comment]
about.license field is not in spdx list: https://spdx.org/licenses/, if it is a typo error, please fix it. If this is not a standard license, then ignore this message.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
please specify in about.license_file the location of the license file in the container, or a url to license for this release of the software.

**Comment by osallou** [comment]
about.license field is not in spdx list: https://spdx.org/licenses/, if it is a typo error, please fix it. If this is not a standard license, then ignore this message.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
please specify in about.license_file the location of the license file in the container, or a url to license for this release of the software.

**Comment by osallou** [comment]
about.license field is not in spdx list: https://spdx.org/licenses/, if it is a typo error, please fix it. If this is not a standard license, then ignore this message.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
please specify in about.license_file the location of the license file in the container, or a url to license for this release of the software.

**Comment by osallou** [comment]
about.license field is not in spdx list: https://spdx.org/licenses/, if it is a typo error, please fix it. If this is not a standard license, then ignore this message.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
about.license field is not in spdx list: https://spdx.org/licenses/, if it is a typo error, please fix it. If this is not a standard license, then ignore this message.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
about.license field is not in spdx list: https://spdx.org/licenses/, if it is a typo error, please fix it. If this is not a standard license, then ignore this message.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
Error is related to softwarename that must be lowercase due to container names restrictions with following regexp: [a-z0-9_-]

ci auto checks should have sent a warning about this but there was a bug I just fixed.
regarding biotools, this is only a warning that can be skipped

Regarding biotools, there is a typo error:

extra.identifiers.biotools => extra.identifier.biotools
(extra s on identifier)

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by ghost** [comment]
I am affraid I got
```
Error processing tar file(exit status 1): write /opt/interproscan/data/gene3d/4.2.0/gene3d_main.hmm.h3p: no space left on device
Build step 'Docker Build and Publish' marked build as failure
```

this needs 25GB to build ;-)
 @ypriverol any chance to increase, see http://jenkins.biocontainers.pro/jenkins/job/container-testci-pr/132/console ?

**Comment by osallou** [comment]
A container is 10gb max

**Comment by osallou** [comment]
Container should not contain data, software only

**Comment by ghost** [comment]
@osallou data folder is not data, these are member databases

**Comment by osallou** [comment]
Databases are data, be it linked data or not.
Anyway, a container size cannot (and should not ) be more than 10gb
Though this can be modified via system config updates, this would need same system updates for users of this image too. And would certainly be rejected on hub too.

**Comment by pcm32** [comment]
Agree with @osallou, anything too heavy as a container becomes unusable unfortunately for end users (personally I try to make sure that, wherever possible, my containers are below the 1 GB mark, and hopefully a lot smaller). 

In this case I would suggest @ola-t that instead of adding the data on the container, you add the logic to obtain that data to the container, plus instructions to users, but not the data (making the size of the container built reasonable). In this way, the user could obtain the data executing some scripts available in your container and leaving them on their host machine filesystem. Documentation (possibly inline as well) should then make explicit where these different data directories should be mounted inside the running container for execution of interproscan. Documentation should also cover how to update the datasets.

Great that you are contributing such a fantastic tool, good luck!

**Comment by ypriverol** [comment]
@ola-t @pcm32 @osallou for the data we can implement a simple mechanism to upload the data to our s3 and leave the data there. We can be 100% sure that the data will remains there. What do you think. You will only need a logic to retrieve the data from there as @pcm32 said.

**Comment by osallou** [comment]
@ypriverol , i am not sure it is in our scope to keep data.volumes are huge, with management if different releases etc...
Data providers such as ebi, ncbi etc..should be kept as base data providers.
I agree that providing a data download script would be enough along container.

**Comment by ghost** [comment]
No problem I will put data tar ball on ftp and user will have to mount as a volume, that’s easy to do

cc: @mscheremetjew

**Comment by osallou** [comment]
No interproscan/5.30-69.0/test-cmds.txt (test file) present, skipping tests

**Comment by ghost** [comment]
At the moment interproscan-data-5.30-69.0.tar.gz is mising one folder, I will ping everyone when is updated for testing

**Comment by osallou** [comment]
No interproscan/5.30-69.0/test-cmds.txt (test file) present, skipping tests

**Comment by ghost** [comment]
`test-cmds.txt` can be add when data tarball will be split to multiple, providing each member database separately

**Comment by osallou** [comment]
No interproscan/5.30-69.0/test-cmds.txt (test file) present, skipping tests

**Comment by osallou** [comment]
No interproscan/5.30-69.0/test-cmds.txt (test file) present, skipping tests

**Comment by osallou** [comment]
No pb, test_cmd is only a comment, tests are more than welcomed, but not
mandatory
Thanks


>

**Comment by osallou** [comment]
No interproscan/5.30-69.0/test-cmds.txt (test file) present, skipping tests

**Comment by osallou** [comment]
No interproscan/5.30-69.0/test-cmds.txt (test file) present, skipping tests

**Comment by ghost** [comment]
@ypriverol now is ready for testing.

**Comment by osallou** [comment]
No interproscan/5.30-69.0/test-cmds.txt (test file) present, skipping tests

**Comment by osallou** [comment]
No interproscan/5.30-69.0/test-cmds.txt (test file) present, skipping tests

**Comment by osallou** [comment]
Perfect, just need to fix Label extra.identifier.biotools

There is still an extra *s*

extra.identifier.biotool

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by ghost** [comment]
How do you mean? `extra.identifier.biotools` or `extra.identifier.biotool`, is complaining now? I removed https://github.com/BioContainers/containers/pull/258/commits/2ad9d62

**Comment by osallou** [comment]
No interproscan/5.30-69.0/test-cmds.txt (test file) present, skipping tests

**Comment by osallou** [comment]
No interproscan/5.30-69.0/test-cmds.txt (test file) present, skipping tests

**Comment by osallou** [comment]
No interproscan/5.30-69.0/test-cmds.txt (test file) present, skipping tests

**Comment by ghost** [comment]
Looks like https://hub.docker.com/r/biocontainers/interproscan/ wasn't build properly, any thoughts how to progress?

**Comment by osallou** [comment]
I can see the container https://hub.docker.com/r/biocontainers/interproscan/tags/

**Comment by ghost** [comment]
It was explained by @ypriverol that there is no latest, all good

**Pull request merged**
