### PR TITLE
seq_crumbs

### PR DESCRIPTION
**Pull request by DavidSharkey**
# Submitting a Container
 
 (If you're requesting for a new container, please check the procedure described [here](https://github.com/BioContainers/containers#241-how-to-request-a-container).  
 
 ## Check BioContainers' Dockerfile [specifications](https://github.com/BioContainers/specs)  
 ## Checklist
 
 1. Misc
 - [x] My tool doesn't exist in [BioConda](#make-sure-your-tool-isnt-already-present-in-bioconda)   
 - [x] The image can be built   
 
 2. [Metadata](#check-biocontainers-dockerfile-metadata)  
 - [x] LABEL base_image  
 - [x] LABEL version
 - [x] LABEL software.version  
 - [x] LABEL about.summary  
 - [x] LABEL about.home  
 - [x] LABEL about.license   
 - [x] MAINTAINER  
 
 3. Extra (optionals)
  - [ ] I have written tests in test-cmds.txt  
  - [ ] LABEL extra.identifier    
  - [ ] LABEL about.documentation   
  - [ ] LABEL about.license_file
  - [ ] LABEL about.tags   
 
 
 ## Check [BioContainers'](https://github.com/BioContainers/specs) Dockerfile metadata

### CODE REVIEW

**Comment by DavidSharkey** [comment]
"sff_extract" is the "default" command. References are at bottom of file.

**Comment by DavidSharkey** [comment]
A response to https://github.com/BioContainers/containers/issues/125

**Comment by osallou** [comment]
Dockerfile is at root directory, should be in softname/softversion/

Seems label version is missing (contaiber version, not the software.version)

In comments, after 'Hertz' there is a non asciii character that may fail the testibg scripts.

**Comment by osallou** [comment]
Hi, container.version label is not needed.
For label version=1.0, just keep 1, no need of major.minor mngt.

Build failed due to non ascii chars. So it seems other chars need to be remove

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 

Maybe small quotes between small sequences?

**Comment by osallou** [comment]
about.license field is a URL. license should be the license identifier (GPL-3.0 for example).

**Comment by osallou** [comment]
please specify in about.license_file the location of the license file in the container, or a url to license for this release of the software.

**Comment by osallou** [comment]
about.license field is not in spdx list: https://spdx.org/licenses/, if it is a typo error, please fix it. If this is not a standard license, then ignore this message.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
about.license field is a URL. license should be the license identifier (GPL-3.0 for example).

**Comment by osallou** [comment]
please specify in about.license_file the location of the license file in the container, or a url to license for this release of the software.

**Comment by osallou** [comment]
about.license field is not in spdx list: https://spdx.org/licenses/, if it is a typo error, please fix it. If this is not a standard license, then ignore this message.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
please specify in about.license_file the location of the license file in the container, or a url to license for this release of the software.

**Comment by osallou** [comment]
about.license field is not in spdx list: https://spdx.org/licenses/, if it is a typo error, please fix it. If this is not a standard license, then ignore this message.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
please specify in about.license_file the location of the license file in the container, or a url to license for this release of the software.

**Comment by osallou** [comment]
about.license field is not in spdx list: https://spdx.org/licenses/, if it is a typo error, please fix it. If this is not a standard license, then ignore this message.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
please specify in about.license_file the location of the license file in the container, or a url to license for this release of the software.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
No seq_crumbs/0.1.9/test-cmds.txt (test file) present, skipping tests

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
No seq_crumbs/0.1.9/test-cmds.txt (test file) present, skipping tests

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
No seq_crumbs/0.1.9/test-cmds.txt (test file) present, skipping tests

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
No seq_crumbs/0.1.9/test-cmds.txt (test file) present, skipping tests

**Comment by osallou** [comment]
Merged, thanks for your work

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
No seq_crumbs/0.1.9/test-cmds.txt (test file) present, skipping tests

**Pull request merged**
