### PR TITLE
Added samtools build for 1.6.0; used ARG in Dockerfile for version

### PR DESCRIPTION
**Pull request by alanhoyle**
This commit adds a new samtools version 1.6.0.

Also, instead of using two hardcoded places for the version in the Dockerfile, it replaces them with an ARG software_version=1.6.0.  

In addition to making it easier to edit the Dockerfile to put in a new version, this lets us build a new samtools version by using a --build-arg parameter on t the docker build command line. 

For example to build samtools 1.7.0, the following command line would work:

 `VERSION=1.7.0 ; docker build --build-arg software_version=$VERSION -t samtools:$VERSION .`

### CODE REVIEW

**Comment by osallou** [comment]
Found a biotools entry matching the software name (https://bio.tools/Samtools), if this is the same software, please add the extra.identifier.biotools label to your Dockerfile

**Comment by alanhoyle** [comment]
...Hmmm, I see that the biocontainers checks might not work with this method?  Might be worth updating the checks in that case?

**Comment by osallou** [comment]
We decided to keep a version directory per software version to keep track of all releases and allow some past releases to be updated for security or other stuff.
Then all containers are automatically built,tagged, tested and pushed.
So it cannot depends on cmd line args.

**Comment by alanhoyle** [comment]
@osallou The samtools 1.6.0 image would be built by an automated `docker build -t samtools:1.6.0 .` What my suggested changed does is twofold:

1.  If a person (or whomever manages automated builds) wants to take the existing Dockerfile and update/add it to build a different version of samtools, they only need to find and edit the version string once on the ARG line, instead of doing a global replace or manually editing it in two locations (both error prone things).  It's a one line change in the Dockerfile to change the version to build.  
1.  If a person wants to use the existing Dockerfile, but build a different version of samtools for their own system, they can specify a different version at build time and not have to edit the Dockerfile at all by doing `docker build --build-arg software_version=$VERSION .`

**Comment by osallou** [comment]
I see your dockerfile install from conda.
Bioconda already builds for biocontainers an image from all its recipes, so image is already available

**Comment by osallou** [comment]
Your pr modifies several files. A PR should impact only 1 container, please rebase your branch against master

**Comment by alanhoyle** [comment]
My apologies, I didn't mean to update an existing pull request.

**Pull request closed without merging**
