### PR TITLE
Added FAMLI v1.0

### PR DESCRIPTION
**Pull request by sminot**
Added a tool  – FAMLI v1.0
For reference: https://www.biorxiv.org/content/early/2018/04/05/295352

### CODE REVIEW

**Comment by osallou** [comment]
Please update Dockerfile to match specs as defined in https://github.com/BioContainers/specs/blob/master/container-specs.md

Some label bames changed some time ago to be inline with bioconda.

**Comment by sminot** [comment]
@osallou I think it may have passed the checks now

**Comment by osallou** [comment]
Why did you set directory version name as 1.0.0-deb?
Version dir name should match the version in the Dockerfile, so only v1.0 in your case.
Some other containers have deb extension because they are imported from debian packages, this is not your case.
Just rename your version dir and it should be ok

**Comment by osallou** [comment]
about.license field is not in spdx list: https://spdx.org/licenses/, if it is a typo error, please fix it. If this is not a standard license, then ignore this message.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
Would also be best to put version in directory vzrsion and dockerfile to 1.0 rather that v1.0, a 'v' is already prefixed automatically.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
You changed your folder to v1.0, instead of 1.0 (which you set in dockerfile)
Folder name and *software.version* must be identical. Sorry for being a little strict with this but this is needed for our automatic scripts.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by sminot** [comment]
The tool is not defined in biotools.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Pull request merged**
