### PR TITLE
added danpos container

### PR DESCRIPTION
**Pull request by nishill**
Added a Dockerfile for the danpos program

### CODE REVIEW

**Comment by ypriverol** [comment]
Can you add the metadata as suggested by the specifications?

**Comment by nishill** [comment]
Alright, I added it. Let me know if there are further changes to be made.

**Comment by osallou** [comment]
Dockerfile should be in a subdirectory matching version, danpos/2.2.2/Dockerfile

**Comment by osallou** [comment]
Invalid structure, Dockerfile must be in directory softwarename/softwareversion/Dockerfile

**Comment by osallou** [comment]
please specify in about.license_file the location of the license file in the container, or a url to license for this release of the software.

**Comment by osallou** [comment]
about.license field is not in spdx list: https://spdx.org/licenses/, if it is a typo error, please fix it. If this is not a standard license, then ignore this message.

**Comment by osallou** [comment]
Found a biotools entry matching the software name (https://bio.tools/danpos), if this is the same software, please add the extra.identifier.biotools label to your Dockerfile

**Comment by osallou** [comment]
Found a biotools entry matching the software name (https://bio.tools/danpos), if this is the same software, please add the extra.identifier.biotools label to your Dockerfile

**Comment by nishill** [comment]
Hmm I'm not sure why it won't build on Jenkins, I assumed it was something to do with the base image

**Comment by osallou** [comment]
You  specified software.version twice
You need software.version=2.2.2 and version=1

**Pull request merged**
