### PR TITLE
update bwa-0.7.17, fastp-0.20.1, fastqc-0.11.9, samtools-1.10

### PR DESCRIPTION
**Pull request by ychenbioinfo**
Hi, 

I am update bwa, fastp, fastqc and samtools with the latest version. 

Best,
Alvin

### CODE REVIEW

**Comment by osallou** [comment]
can't modify multiple containers in a same pull request

**Comment by ychenbioinfo** [comment]
Why? Because of the limitation of the CI/CD?

**Comment by osallou** [comment]
Yes, limitation is related to ci and pr management.

**Comment by ychenbioinfo** [comment]
Okay, will do

**Comment by osallou** [comment]
can't modify multiple containers in a same pull request

**Pull request closed without merging**
