### PR TITLE
Add samtools 1.7

### PR DESCRIPTION
**Pull request by magicDGS**

### CODE REVIEW

**Comment by osallou** [comment]
license field is a URL. license should be the license identifier (GPL-3.0 for example).

**Comment by osallou** [comment]
please specify in license_file the location of the license file in the container, or a url to license for this release of the software.

**Comment by osallou** [comment]
license field is not in spdx list: https://spdx.org/licenses/, if it is a typo error, please fix it. If this is not a standard license, then ignore this message.

**Comment by osallou** [comment]
Found a biotools entry matching the software name (https://bio.tools/Samtools), if this is the same software, please add the bioools label to your Dockerfile

**Comment by osallou** [comment]
Hi, there is already a bioconda package/container for samtools 1.7

**Comment by bgruening** [comment]
@magicDGS as @osallou already mentioned, can you try this container instead? https://quay.io/repository/biocontainers/samtools?tab=tags

**Comment by magicDGS** [comment]
@osallou and @bgruening - I can use the repository from quay.io but where is the Dockerfile for it?

Sometimes I need to look at the container configuration, and also I would like to use the same versioning name as the samtools repository. The one in quay.io is samtools:1.7--0, which is a wierd versioning name.

**Comment by bgruening** [comment]
These containers are automatically generated out of conda packages, so there is no Dockerfile at all.
All containers are generated in the same way, with a predictable namespace. What you call wired is a predicable name and version that can be automatically retrieved by workflow managers without knowing the exact name of the container. `--0` is a build number, we are trying to never overwrite or remove a container to stay reproducible.

**Comment by magicDGS** [comment]
Ok, now I understand the `--0`. So that means that every package has a `--0` append to the first build? In that case, is it safe to pull the `${version}--0` for any generated container? And what are the differences between builds?

**Pull request closed without merging**
