### PR TITLE
Dockerfile for bamdst

### PR DESCRIPTION
**Pull request by tamuanand**
https://github.com/BioContainers/containers/issues/456

 # Submitting a Container
 
 (If you're requesting for a new container, please check the procedure described [here](https://github.com/BioContainers/containers#241-how-to-request-a-container).  
 
 ## Check BioContainers' Dockerfile [specifications](https://github.com/BioContainers/specs)  
 ## Checklist
 
 1. Misc
 - [ ] My tool doesn't exist in [BioConda](#make-sure-your-tool-isnt-already-present-in-bioconda)   
 - [ ] The image can be built   
 
 2. [Metadata](#check-biocontainers-dockerfile-metadata)  
 - [ ] LABEL base_image  
 - [ ] LABEL version
 - [ ] LABEL software.version  
 - [ ] LABEL about.summary  
 - [ ] LABEL about.home  
 - [ ] LABEL about.license   
 
 ## Check [BioContainers'](https://github.com/BioContainers/specs) Dockerfile metadata

### CODE REVIEW

**Comment by osallou** [comment]
Should be in directiry with version ie bamdst/1.0.9/Dockerfile

**Comment by tamuanand** [comment]
@osallou  -- Done 

Could you please check and let me know

> Should be in directiry with version ie bamdst/1.0.9/Dockerfile

**Comment by osallou** [comment]
@tamuanand merged, container will be available soon

**Comment by tamuanand** [comment]
Thanks a lot @osallou 

Just curious (as this is first time for creating biocontainer)
- What's typical turnaround time for container to show up in quay.io - is it 48 hrs?
- will this also have something available via bioconda or is it just the biocontainer in quay.io

Thanks once again

**Comment by tamuanand** [comment]
Hi @ypriverol @osallou @bgruening 

Sorry for the trouble - would you know when this would be available for download via quay.io

Thanks in advance

**Comment by osallou** [comment]
Containers from github repo are in dockerhub  , on quayio this is for conda based packages

**Comment by osallou** [comment]
https://hub.docker.com/r/biocontainers/bamdst/tags

**Comment by tamuanand** [comment]
Thanks @osallou

**Pull request merged**
