### PR TITLE
Add Dockerfile for TCRdock v1.0.0

### PR DESCRIPTION
**Pull request by eliasball**
# Submitting a Container
 
 ## Checklist
 
 1. Misc
 - [x] My tool doesn't exist in [BioConda](#make-sure-your-tool-isnt-already-present-in-bioconda)   
 - [x] The image can be built
  - To build the image, `--ulimit nofile=262144:262144` needs to provided to `docker build`. How should this be done in Biocontainers?
 
 2. [Metadata](#check-biocontainers-dockerfile-metadata)  
 - [x] LABEL base_image  
 - [x] LABEL version
 - [x] LABEL software.version  
 - [x] LABEL about.summary  
 - [x] LABEL about.home  
 - [x] LABEL about.license   
 - [x] MAINTAINER  
 
 3. Extra (optionals)
  - [ ] I have written tests in test-cmds.txt  
  - [ ] LABEL extra.identifier    
  - [x] LABEL about.documentation   
  - [x] LABEL about.license_file
  - [x] LABEL about.tags

### CODE REVIEW

**Comment by eliasball** [comment]
Hey!
One more thing before the PR could potentially be accepted: As mentioned above, to build the image, `--ulimit nofile=262144:262144` needs to provided to `docker build`. How should this be done in Biocontainers?

**Comment by eliasball** [comment]
Also, the software provided is not my software, but I forked the repo and added some important files to make the docker container build. Is it alright to provide only the links to my fork in the LABELS?

**Comment by mboudet** [comment]
Hmm, it seems to build fine on our end without the --ulimit. (Which is great, because there are not easy way to include those in the build process).

Not sure regarding the fork. Is the maintainer not interested in merging your modifications in the main repo?

**Comment by eliasball** [comment]
I see, this is good news! The --ulimit was related to a bug when installing cudatoolkit (https://github.com/mamba-org/mamba/issues/2501#issuecomment-1582182711) and the fix simply requires it to be not set too high. Great that it works without on our build system!

Regarding the fork: I haven't contacted the maintainer about this topic, as it was simpler to just devise the necessary env.yml file myself and have control over release versioning. If this is wished for I could do this however.

**Comment by mboudet** [comment]
Well, I feel like it would be cleaner to link to the main repo. If the maintainer does not wish to incorporate the modifications, we can proceed as it is.

**Comment by eliasball** [comment]
Alright, I will open a PR for the main repo and contact the maintainer, I will reach out once everything works, thanks a lot! :)

**Pull request closed without merging**
