### PR TITLE
Fix dead links

### PR DESCRIPTION
**Pull request by stianlagstad**
Fixing a dead link.

### CODE REVIEW

**Comment by osallou** [comment]
You're trying to update a file not related to a container: README.md, this is forbidden

**Comment by osallou** [comment]
You're trying to update a file not related to a container: README.md, this is forbidden

**Comment by osallou** [comment]
You're trying to update a file not related to a container: README.md, this is forbidden

**Comment by osallou** [comment]
You're trying to update a file not related to a container: README.md, this is forbidden

**Comment by osallou** [comment]
You're trying to update a file not related to a container: README.md, this is forbidden

**Comment by osallou** [comment]
You're trying to update a file not related to a container: README.md, this is forbidden

**Comment by stianlagstad** [comment]
Ref #357

**Pull request merged**
