### PR TITLE
Add meme-suite 4.12.0

### PR DESCRIPTION
**Pull request by TShimko126**
Added MEME Suite version 4.12.0 (http://meme-suite.org/index.html)

For reference:
Timothy L. Bailey, et al. (2009) _MEME SUITE: tools for motif discovery and searching_. Nucleic Acids Research, 37:W202-W208.

### CODE REVIEW

**Comment by osallou** [comment]
about.license field is a URL. license should be the license identifier (GPL-3.0 for example).

**Comment by osallou** [comment]
please specify in about.license_file the location of the license file in the container, or a url to license for this release of the software.

**Comment by osallou** [comment]
about.license field is not in spdx list: https://spdx.org/licenses/, if it is a typo error, please fix it. If this is not a standard license, then ignore this message.

**Comment by osallou** [comment]
No biotools label defined, please check if tool is not already defined in biotools (https://bio.tools) and add extra.identifier.biotools label if it exists. If it is not defined, you can ignore this comment.

**Comment by bgruening** [comment]
meme is already available as https://quay.io/repository/biocontainers/meme?tag=latest&tab=tags

**Comment by TShimko126** [comment]
@bgruening: Thanks for the heads up! It didn't show in searches of the repo here or the registry at https://biocontainers.pro/registry/#/. Any ideas on why that might be? Asking so I don't duplicate available tools on future contributions.

**Comment by bgruening** [comment]
We need to work on the registry, sorry. This will be done in the next months. In the meantime, please use quay.io. Thanks!

**Pull request closed without merging**
