### PR TITLE
Update to PeptideShaker 1.16.16

### PR DESCRIPTION
**Pull request by CarlosHorro**
This PR is only a version update to PeptideShaker 1.16.16.
No major changes needed but updating references to this new version.

### CODE REVIEW

**Comment by osallou** [comment]
please remove those .DS_Store from PR

**Comment by CarlosHorro** [comment]
Sorry, it has been removed now.

**Comment by osallou** [comment]
remains one at root  ;-)

**Comment by osallou** [comment]
license field is a URL. license should be the license identifier (GPL-3.0 for example).

**Comment by osallou** [comment]
please specify in license_file the location of the license file in the container, or a url to license for this release of the software.

**Comment by osallou** [comment]
license field is not in spdx list: https://spdx.org/licenses/, if it is a typo error, please fix it. If this is not a standard license, then ignore this message.

**Comment by osallou** [comment]
Found a biotools entry matching the software name (https://bio.tools/PeptideShaker), if this is the same software, please add the biotools label to your Dockerfile

**Comment by bgruening** [comment]
There are already containers here: https://quay.io/repository/biocontainers/peptide-shaker?tab=tags
So I think we should update the Bioconda recipe instead.

**Comment by CarlosHorro** [comment]
Hi @bgruening 
I've already made a PR to Bioconda: 
https://github.com/bioconda/bioconda-recipes/pull/8247 
But would be also necessary to update this repo for users of https://hub.docker.com/r/biocontainers/peptideshaker/ , right?

**Comment by ypriverol** [comment]
These are two ways of building our containers. I guess both ways are right @CarlosHorro . I remember the first time I work with peptideShacker developers in the Dockefile based container, we put a lot of emphasis in been able to forward the GUI interface of peptideshacker.

**Comment by bgruening** [comment]
@CarlosHorro cool! You container and package will be available in a few minutes.

**Comment by bgruening** [comment]
Container and Conda is online.
Thanks @CarlosHorro!

**Comment by CarlosHorro** [comment]
Thank you all. Then, do I cancel this PR? or maybe would it be nice to have this repo also updated?

**Comment by ypriverol** [comment]
No. This will be integrated as dockerfile container

**Comment by CarlosHorro** [comment]
Sorry @ypriverol , did you mean I must not cancel this PR? or I must not update this repo?

**Comment by ypriverol** [comment]
I mean You must not cancel this PR

**Comment by osallou** [comment]
license field is a URL. license should be the license identifier (GPL-3.0 for example).

**Comment by osallou** [comment]
please specify in license_file the location of the license file in the container, or a url to license for this release of the software.

**Comment by osallou** [comment]
license field is not in spdx list: https://spdx.org/licenses/, if it is a typo error, please fix it. If this is not a standard license, then ignore this message.

**Comment by osallou** [comment]
Found a biotools entry matching the software name (https://bio.tools/PeptideShaker), if this is the same software, please add the biotools label to your Dockerfile

**Pull request merged**
