### PR TITLE
vg 1.23.0+ds-1

### LINKED ISSUE #360: Debian based biocontainer for VG
https://tracker.debian.org/pkg/vg

Thanks!

### PR DESCRIPTION
**Pull request by mr-c**
Fixes #360 

 # Submitting a Container
 
 ## Checklist
 
 1. Misc
 - [x] My tool doesn't exist in [BioConda](#make-sure-your-tool-isnt-already-present-in-bioconda)   
 - [x] The image can be built   
 
 2. [Metadata](#check-biocontainers-dockerfile-metadata)  
 - [x] LABEL base_image  
 - [x] LABEL version
 - [x] LABEL software.version  
 - [x] LABEL about.summary  
 - [x] LABEL about.home  
 - [x] LABEL about.license   
 - [x] MAINTAINER  
 
 3. Extra (optionals)
  - [x] I have written tests in test-cmds.txt  
  - [ ] LABEL extra.identifier    
  - [x] LABEL about.documentation   
  - [x] LABEL about.license_file
  - [ ] LABEL about.tags

### CODE REVIEW

**Comment by osallou** [comment]
I see you base your image on debian testing. Issue is package can change many times and can even be removed in future.

**Comment by mr-c** [comment]
@osallou Correct, it isn't available in a released version of Debian and I was unable to get a backport working.

If that is an issue, we can tell apt to use `deb https://snapshot.debian.org/archive/debian/20200331T024956Z/ bullseye main`

**Comment by osallou** [comment]
humum, the plus sign in version shows a bug in our CI scripts... it is somehow mapped to a space, create issues in other scripts. I gonna investiguate

**Comment by osallou** [comment]
plus sign is not allowed in docker name/tags,  so you should:

1) rename version dir
2) update accordingly version in Dockerfile

you could "skip" the plus or replace with *-plus* (this is what I do for autoupdate of debian packages)

**Comment by mr-c** [comment]
Thanks @osallou I've made your suggested change

Thanks @biocontainers-bot I had already checked and I could find no entry at bio.tools

**Pull request merged**
