### PR TITLE
Adds X!Tandem 17-02-01-4

### PR DESCRIPTION
**Pull request by jgriss**
# Submitting a Container
 
Updated version of X!Tandem (17-02-01-4)

**Note:** The Dockerfile currently directly downloads X!Tandem from the GPMDB FTP server. This is not stable. The new X!Tandem ZIP file (referenced in the Dockerfile) should be made available through the Tandem releases on the software archive. The respective URL is already in the Dockerfile but commented out.

### CODE REVIEW

**Comment by osallou** [comment]
As per checks, software.name is invalid, should be named tandem as per directory name

you can add a label software.upstream_name to specify "real" name.

software.name is used to name the container, but container naming rules limit at [a-z0-9] characters.

**Comment by osallou** [comment]
can't modify multiple containers in a same pull request

**Comment by osallou** [comment]
No tandem/17-02-01-4/test-cmds.txt (test file) present, skipping tests

**Comment by ypriverol** [comment]
Can I merge this PR @osallou

**Comment by osallou** [comment]
@ypriverol sure!

**Comment by osallou** [comment]
No tandem/17-02-01-4/test-cmds.txt (test file) present, skipping tests

**Pull request merged**
