### PR TITLE
Add PaddleHelix CPU and GPU metadata YAML files

### PR DESCRIPTION
**Pull request by rijulsr**
# Submitting a Container
 
 (If you're requesting for a new container, please check the procedure described [here](https://github.com/BioContainers/containers#241-how-to-request-a-container).  
 
 ## Check BioContainers' Dockerfile [specifications](https://github.com/BioContainers/specs)  
 ## Checklist
 
 1. Misc
 - [x] My tool doesn't exist in [BioConda](#make-sure-your-tool-isnt-already-present-in-bioconda)   
 - [x] The image can be built   
 
 2. [Metadata](#check-biocontainers-dockerfile-metadata)  
 - [x] LABEL base_image  
 - [x] LABEL version
 - [x] LABEL software.version  
 - [x] LABEL about.summary  
 - [x] LABEL about.home  
 - [ ] LABEL about.license   
 - [x] MAINTAINER  
 
 3. Extra (optionals)
  - [ ] I have written tests in test-cmds.txt  
  - [ ] LABEL extra.identifier    
  - [ ] LABEL about.documentation   
  - [ ] LABEL about.license_file
  - [ ] LABEL about.tags   
 
 
 ## Check [BioContainers'](https://github.com/BioContainers/specs) Dockerfile metadata

### CODE REVIEW

**Comment by rijulsr** [comment]
This repository contains a Dockerfile for building a Docker image with PaddleHelix and its dependencies.

**Comment by mboudet** [comment]
Hello,

I'm not really sure what this PR is about. Are you trying to add a new tool on the biocontainer repository?
If so, you'll need to to submit a PR containing the Dockerfile itself so that the CI will build it.

Does this tool exists in bioconda? If so, there should already be a docker image built.

**Comment by rijulsr** [comment]
My intent with this PR is to add a new tool on the niocontainer repository and no this doesn't exist in bioconda.

**Comment by mboudet** [comment]
Ok, so if you want to add a new tool, you need to provide a dockerfile (see https://github.com/BioContainers/containers/pull/573/files)

I would however advise trying to create a conda package instead, for increased usability (SEE https://bioconda.github.io/contributor/index.html). It would create both a conda package, a docker image, and a singularity image.

**Comment by mboudet** [comment]
Please follow the specs: 
* 1 PR for each Dockerfile
* Dockerfiles should be called 'Dockerfile'
* Dockerfiles should be placed in a folder with the path 'toolname/tool_version/Dockerfile' (matching label software and software.version
* They should also contain the required labels (https://github.com/BioContainers/specs/blob/master/container-specs.md)

**Comment by rijulsr** [comment]
Okay, So Do I need to carry out the whole process again?

**Comment by mboudet** [comment]
You should do two separated PR, yes. Also, no need for the .yaml files.

**Comment by rijulsr** [comment]
Okay Will do that

**Pull request closed without merging**
