### PR TITLE
Add proteoQC

### PR DESCRIPTION
**Pull request by jingyuanhu01**
Hi,

I am very new to this, can I add this docker to biocontainer?

Thanks,

### CODE REVIEW

**Comment by jingyuanhu01** [comment]
The documentation and usage can be found here: 
http://bioconductor.org/packages/release/bioc/html/proteoQC.html

**Comment by ypriverol** [comment]
Can use use our base image biocontainers/biocontainers instead of ubuntu?

**Comment by prvst** [comment]
Also, change the version number to a integer (1, 2, 3, etc...) and add the tool to the path, that way you can remove the entry point command

**Comment by jingyuanhu01** [comment]
I've made the change. However, when I tried the CMD [COMMAND], I cannot pass arguments for the shell script. Therefore I kept the entry point, and I hope it's OK.

**Comment by osallou** [comment]
I see you set USER=root, is it really necessary for the software ? If not, you should set default biocontainers *biodocker* user before ending Dockerfile .

    USER biodocker


You should also move your Dockerfile in a subdir

mysoftware/myversion/Dockerfile  , for you proteoqc/1/Dockerfile

**Comment by ypriverol** [comment]
Hi @JasperYH any progress here? We are more than happy to help you.

**Pull request closed without merging**
